### ISSUE TITLE
ghcjs stack Cabal-1.22.4.0 failed during the configure step

### ISSUE THREAD

**Issue by UrKr** [ghcjs/ghcjs#470]
As recommended I tried using building ghcjs via a stack project, but I get the following error at some point after running stack setup and stack setup running ghcjs-boot

I found this issue, which I'm not sure is the same, and tried installing node 4 instead of node 5, but the error persists. 
#https://github.com/ghcjs/ghcjs/issues/462

I'm running ubuntu 14.04. 

This is the error:

```
Failed to install Cabal-1.22.4.0              
cabal: Error: some packages failed to install:
Cabal-1.22.4.0 failed during the configure step. The exception was:
user error (The package 'Cabal' requires Cabal library version -any && >=1.10
but no suitable version is installed.)        
ghcjs-boot: error running: /home/urban/.cabal/bin/cabal --config-file /home/urban/.ghcjs/x86_64-linux-0.2.0.20151230.3-7.10.2/ghcjs/cabalBootConfig --ignore-sandbox install ./boot/cabal/Cabal --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /home/urban/.stack/programs/x86_64-linux/ghcjs-0.2.0.20151230.3_ghc-7.10.2/src/.stack-work/install/x86_64-linux/lts-3.20/7.10.2/bin/ghcjs --with-hc-pkg /home/urban/.stack/programs/x86_64-linux/ghcjs-0.2.0.20151230.3_ghc-7.10.2/src/.stack-work/install/x86_64-linux/lts-3.20/7.10.2/bin/ghcjs-pkg --prefix /home/urban/.ghcjs/x86_64-linux-0.2.0.20151230.3-7.10.2/ghcjs --enable-documentation --haddock-html --haddock-hyperlink-source --enable-shared --enable-library-profiling --root-cmd /home/urban/.ghcjs/x86_64-linux-0.2.0.20151230.3-7.10.2/ghcjs/run.sh
exit status: 1                                
stderr: Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.             
cabal: Error: some packages failed to install:
Cabal-1.22.4.0 failed during the configure step. The exception was:
user error (The package 'Cabal' requires Cabal library version -any && >=1.10
but no suitable version is installed.) 
```

This is my stack.yaml, though I'm unsure if it's relevant:

```
# This file was automatically generated by stack init
# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration/

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-3.20

# Local packages, usually specified by relative directory name
packages:
- '.'
# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

compiler: ghcjs-0.2.0.20151230.3_ghc-7.10.2
compiler-check: match-exact
setup-info:
 ghcjs:
  source:
   ghcjs-0.2.0.20151230.3_ghc-7.10.2:
    url: "https://github.com/nrolland/ghcjs/releases/download/v.0.2.0.20151230.3/ghcjs-0.2.0.20151230.3.tar.gz"
```
