### ISSUE TITLE
Issue with Cabal built via ghcjs: does not pass ghc-options to ghcjs

### ISSUE THREAD

**Issue by mgsloan** [ghcjs/ghcjs#492]
With this ghcjs version and Cabal-1.24:

```
compiler: ghcjs-0.2.0.20160315_ghc-7.10.2
# compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160315_ghc-7.10.2:
        url: "https://github.com/nrolland/ghcjs/releases/download/v.0.2.0.20160315/ghcjs-0.2.0.20160315.tar.gz"
```

When I pass `--ghc-options -ddump-splices` (or whatever) to essentially `runhaskell Setup.hs configure`, they do not get provided to `ghc`.  With stack, this can be verified by running `stack build --ghc-options some-options -v --cabal-verbose` and seeing it present in the configure invocation but not the ghc invocation.

Sorry for the lack of repro, I can try to get a minimal public repro if that's helpful (if others can't reproduce it directly on their own projects)
