### ISSUE TITLE
Main test file must be called Main.hs in order to run stack test

### ISSUE THREAD

**Issue by mchaver** [ghcjs/ghcjs#511]
I usually call the main test file `Spec.hs`. For some reason when testing with `stack test` and GHCJS I get this error:

```
Warning: output was redirected with -o, but no output will be generated
because there is no Main module.
```

I do have a `main :: IO ()` function in `Spec.hs` but it does seem to work. If I change the file name to `Main.hs` along with the `main-is` in Cabal. Then I can run the test.

Here is the compiler I am using in stack.yaml:

```
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3
```
