### ISSUE TITLE
Can't install Aeson-0.8.0.2

### ISSUE THREAD

**Issue by mchaver** [ghcjs/ghcjs#513]
In ghcjs.cabal it looks like it supports `aeson-0.8.0.2` : `aeson >= 0.7 && < 0.10`, but for some reason I can only get it to install with `aeson-0.9.0.1`. At the moment I am just trying it in a test project, this is what my cabal file looks like:

```
library
  hs-source-dirs:      src
  exposed-modules:     Lib
  build-depends:       base >= 4 && < 5
                              , ghcjs-base
                              , aeson == 0.8.0.2
  default-language:    Haskell2010
```

I get this error when using `cabal install --ghcjs`:

```
next goal: ghcjs-base (dependency of ghcjs-test-0.1.0.0)
rejecting: ghcjs-base-0.2.0.0/installed-5c7... (conflict: aeson==0.8.0.2,
ghcjs-base => aeson==0.9.0.1/installed-b24...)
Dependency tree exhaustively searched.
```

Currently most of our system depends on `0.8.0.2`. We had previously tried out `aeson-0.9.0.1` but had run into a few breaking issues. We would like to try to avoid that version.

I tried it with these compilers:

- https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
- https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160717_ghc-7.10.3.tar.gz

**Comment by mchaver** [comment]
My ultimate goal is to use it with stack. If I put no restriction on `aeson` in cabal, no extra-deps, and use `stack build` then run `stack list-dependencies` it lists `aeson 0.11.2.1`, but if I set `aeson == 0.11.2.1` in the cabal file I get the this error:

```
--  Failure when adding dependencies:    
      aeson: needed (==0.11.2.1), 0.9.0.1 found (latest applicable is 0.11.2.1)
    needed for package ghcjs-test-0.1.0.0
```

If I try it with `cabal install --ghcjs` I get this:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ghcjs-test-0.1.0.0 (user goal)
next goal: aeson (dependency of ghcjs-test-0.1.0.0)
rejecting: aeson-0.9.0.1/installed-b24..., aeson-1.0.0.0 (conflict: ghcjs-test
=> aeson==0.11.2.1)
trying: aeson-0.11.2.1
next goal: ghcjs-base (dependency of ghcjs-test-0.1.0.0)
rejecting: ghcjs-base-0.2.0.0/installed-5c7... (conflict: aeson==0.11.2.1,
ghcjs-base => aeson==0.9.0.1/installed-b24...)
Dependency tree exhaustively searched.
```

**Comment by spl** [comment]
Is it possible to use `stack setup` with an appropriate `stack.yaml` referencing the `ghcjs` URL instead of trying to build with `stack build`?

**Comment by mchaver** [comment]
Here is what my `stack.yaml` with `aeson == 0.11.2.1`, `ghcjs-base` and `base` as dependencies in cabal:

```
resolver: lts-6.14

compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3

packages:
- '.'
- location:
    git: git@github.com:ghcjs/ghcjs-ffiqq.git
    commit: b52338c2dcd3b0707bc8aff2e171411614d4aedb
  extra-dep: true
extra-deps: []
extra-package-dbs: []
```

If I run `stack setup` I get this:

```
stack will use a locally installed GHCJS
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHCJS and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
```

I have another issue here for stack, it might have some implications on this issue but I am not sure yet: https://github.com/commercialhaskell/stack/issues/2556
