### ISSUE TITLE
Does ghcjs create runghcjs?

### ISSUE THREAD

**Issue by crocket** [ghcjs/ghcjs#520]
My stack file contains
```
resolver: lts-7.1
compiler: ghcjs-0.2.1.9007001_ghc-8.0.1
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007001_ghc-8.0.1:
        url: http://tolysz.org/ghcjs/ghc-8.0-2016-09-26-lts-7.1-9007001-mem.tar.gz
        sha1: e640724883238593e2d2f7f03991cb413ec0347b
```

Now, flycheck-haskell fails to work because there is no `runghcjs`.
I suspect ghcjs didn't create runghcjs or tolysz forgot to include it.
