### ISSUE TITLE
error with GHCJS 8: hs_ToFixedLength is not defined

### ISSUE THREAD

**Issue by mmaz** [ghcjs/ghcjs#521]
Hi, I'm using [`formatting`](http://hackage.haskell.org/package/formatting) and seeing the following error in GHCJS 8's generated code when trying to format a `Float` to fixed length (both in-browser and via `node`):

```bash
$ node error.jsexe/all.js 
"0.1234"
uncaught exception in Haskell main thread: ReferenceError: h$_hs_ToFixedLength is not defined
ReferenceError: h$_hs_ToFixedLength is not defined
    at h$$By (.../error.jsexe/all.js:53192:11)
    at h$runThreadSlice (.../error.jsexe/all.js:9606:11)
    at h$runThreadSliceCatch (.../error.jsexe/all.js:9561:12)
    at h$mainLoop (.../error.jsexe/all.js:9554:9)
    at .../error.jsexe/all.js:10205:13
    at .../error.jsexe/all.js:23263:17
    at FSReqWrap.strWrapper (fs.js:568:5)
```

Here is the testcase that throws the exception:

```haskell
import           Data.Text (Text)
import qualified Data.Text as T
import           Formatting hiding (text)

tshow :: Show a => a -> Text
tshow = T.pack . show

tfloat :: Float -> Text
tfloat = sformat (fixed 2)

main :: IO ()
main = do
  let x = 0.1234
  print $ tshow x
  print $ tfloat x
```

I'm using the following version of GHCJS (through stack, via [this post](https://www.reddit.com/r/haskell/comments/54knub/ghcjs_dedupe/)):

```
resolver: nightly-2016-09-08
compiler: ghcjs-0.2.1.9007001_ghc-8.0.1
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007001_ghc-8.0.1:
          url: http://tolysz.org/ghcjs/ghc-8.0-2016-09-26-lts-7.1-9007001-mem.tar.gz
          sha1: e640724883238593e2d2f7f03991cb413ec0347b
```

For comparison, with  GHC 8:
```bash
$ stack Testcase.hs
"0.1234"
"0.12"
```

Do you have any suggestions on what to try? Thanks!
