### ISSUE TITLE
REPL crashes on ghcjs-base.

### ISSUE THREAD

**Issue by crocket** [ghcjs/ghcjs#542]
I inserted the following `stack.yaml` into ghcjs-base and executed `stack ghci` in ghcjs-base.

```yaml
resolver: lts-6.20
compiler: ghcjs-0.2.0.9006020_ghc-7.10.3
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006020_ghc-7.10.3:
        url: http://ghcjs.tolysz.org/lts-6.20-9006020.tar.gz
        sha1: a6cea90cd8121eee3afb201183c6e9bd6bacd94a

packages:
- '.'

extra-deps: []

flags: {}

extra-package-dbs: []
```

I had to push through multiple instances of segmentation faults to launch REPL on ghcjs-base. Does this issue still exist?
