### ISSUE TITLE
nightly builds of branch ghc-8.0 vs. stack

### ISSUE THREAD

**Issue by fisx** [ghcjs/ghcjs#579]
In order for the nightly build of branch ghc-8.0 to work on my project, I had to:

- download http://ghcjs.luite.com/ghc-8.0-20170411.tar.gz
- untar it, replace the stack.yaml with the following, and tar it again:

```yaml
resolver: lts-8.9

extra-deps:
- haddock-api-2.17.3.1
- aeson-0.11.3.0
- optparse-applicative-0.12.1.0
```

- add this to my project's stack.yaml:

```yaml
compiler: ghcjs-0.2.1.20170411_ghc-8.0.2
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.20170411_ghc-8.0.2:
#        url: "http://ghcjs.luite.com/ghc-8.0-20170411.tar.gz"
#        sha1: bc590645f6575276ea4d2aaa206c6d96ba71efed
        url: "/home/.../ghc-8.0-20170411.tar.gz"
```

Now `stack setup` is building away happily (I will know whether it worked after lunch.

I am posting this for two reasons: (1) where can I submit the updated stack.yaml as a patch?  (2) if you had the same problem, there you go.  (-:
