### ISSUE TITLE
Possible ghcjs-8.4.0.1 issue with stack.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [ghcjs/ghcjs#652]
I'm getting the following when using `stack build` in a project.

```

compiler: ghcjs-0.2.1.9011008_ghc-8.4.1

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9011008_ghc-8.4.1:
          url: https://github.com/alexanderkjeldaas/ghcjs/releases/download/ghc-8.4.1-rc2/ghcjs.tar.gz
          sha1: 79051ecce5b9d4feaf9107c00178283e062864e1
```

```
$ /home/devel/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.2.0.1_ghcjs-8.4.0.1_ghc-8.4.2.20180505 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.2.0.1_ghcjs register
uncaught exception in Haskell main thread: TypeError: Cannot read property 'isSymbolicLink' of null
TypeError: Cannot read property 'isSymbolicLink' of null
    at h$directory_getFileStatusIsSymbolicLink (/home/devel/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.2.0.1_ghcjs-8.4.0.1_ghc-8.4.2.20180505:27034:13)
    at h$directoryzm1zi3zi1zi5zm2mI4y4KffND9ZZv04iHI3IxZCSystemziDirectoryziInternalziGHCJSzizdwfileTypeFromMetadata_e (/home/devel/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.2.0.1_ghcjs-8.4.0.1_ghc-8.4.2.20180505:115941:11)
    at h$runThreadSlice (/home/devel/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.2.0.1_ghcjs-8.4.0.1_ghc-8.4.2.20180505:8625:11)
    at h$runThreadSliceCatch (/home/devel/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.2.0.1_ghcjs-8.4.0.1_ghc-8.4.2.20180505:8578:12)
    at h$mainLoop (/home/devel/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.2.0.1_ghcjs-8.4.0.1_ghc-8.4.2.20180505:8573:9)
    at /home/devel/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.2.0.1_ghcjs-8.4.0.1_ghc-8.4.2.20180505:9141:13
    at h$handleErrnoC (/home/devel/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.2.0.1_ghcjs-8.4.0.1_ghc-8.4.2.20180505:6032:9)
    at /home/devel/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.2.0.1_ghcjs-8.4.0.1_ghc-8.4.2.20180505:27006:13
    at FSReqWrap.oncomplete (fs.js:152:21)
```
