### ISSUE TITLE
uncaught exception in Haskell thread: Error: invalid big integer: incorrect number of limbs

### ISSUE THREAD

**Issue by RobertFischer** [ghcjs/ghcjs#662]
I am getting a lot of these issues with this build:

```yaml
resolver: lts-9.21
compiler: ghcjs-0.2.1.9009021_ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9009021_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9009021.tar.gz
        sha1: b1740c3c99e5039ac306702894cd6e58283f4d31
```

They look like this:

```
uncaught exception in Haskell thread: Error: invalid big integer: incorrect number of limbs ghcjs.js:7093:9
h$ghcjsbn_assertValid_b@http://localhost:8080/ghcjs.js:19825:11
h$ghcjsbn_quotRem_bw@http://localhost:8080/ghcjs.js:20376:3
h$_hs_bytestring_long_long_uint_dec@http://localhost:8080/ghcjs.js:26191:9
h$$bBA@http://localhost:8080/ghcjs.js:99772:11
h$runThreadSlice@http://localhost:8080/ghcjs.js:8049:11
h$runThreadSliceCatch@http://localhost:8080/ghcjs.js:7999:12
h$mainLoop@http://localhost:8080/ghcjs.js:7994:9
run@webpack-internal:///./node_modules/setimmediate/setImmediate.js:48:9
runIfPresent@webpack-internal:///./node_modules/setimmediate/setImmediate.js:83:11
onGlobalMessage@webpack-internal:///./node_modules/setimmediate/setImmediate.js:125:9
```

Any idea what's going on, or how I can fix it?
