### ISSUE TITLE
ghcjs 8.4 javascript function name expression FFI creates an extra parameter with zero for JSVal and JSString

### ISSUE THREAD

**Issue by louispan** [ghcjs/ghcjs#666]
In GHCJS8.4 every JString comparison is always true.

Using the following ghcjs 8.4 stack.yaml,

```
resolver: nightly-2018-04-21

# ghcjs 8.4 doesn't include ghcjs-base
extra-deps:
 - git: git@github.com:ghcjs/ghcjs-base.git
   commit: 4560541fbab5b77ee34d0348ec04bb1dda8e5db3

# compiler: ghcjs-0.2.0.9011009_ghc-8.4.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9011009_ghc-8.4.1:
           url: https://github.com/alexanderkjeldaas/ghcjs/releases/download/fghcjs-8.4.1/ghcjs.tar.gz
```

Code generated by javascript FFI creates an extra parameter with an extra zero for every string

Eg. Usage of [JSString Ord instance](https://github.com/ghcjs/ghcjs-base/blob/4560541fbab5b77ee34d0348ec04bb1dda8e5db3/Data/JSString.hs#L224):

```
instance Ord JSString where
  compare x y = compareStrings x y

compareStrings :: JSString -> JSString -> Ordering
compareStrings x y = tagToEnum# (js_compare x y +# 1#)
{-# INLINE compareStrings #-}

foreign import javascript unsafe
  "h$jsstringCompare" js_compare :: JSString -> JSString -> Int#
```

Get generated into the following (h$jsstringCompare has *4* parameters instead of *2*, the extra parameters passed as zero)

```
function h$$xh()
{
  var a = h$r1;
  var b = h$stack[(h$sp - 1)];
  h$sp -= 2;
  var c = h$jsstringCompare(b, 0, a, 0);
  var d = c;
  if((d === 1))
  {
    return h$e(h$baseZCGHCziShowzizdfShowBool2);
  }
  else
  {
    return h$e(h$baseZCGHCziShowzizdfShowBool4);
  };
};
```

Since [h$jsstringCompare](https://github.com/ghcjs/ghcjs-base/blob/4560541fbab5b77ee34d0348ec04bb1dda8e5db3/jsbits/jsstring.js#L1015) is implemented as follows, only the first two parameters are used, with the 2nd parameter as zero integer. The string comparison with zero integer will is always false, meaning h$jsstringCompare always return 0 from the function, which gets converted to EQ.

```
function h$jsstringCompare(x, y) {
    TRACE_JSSTRING("compare: '" + x + "' '" + y + "'");
    return (x<y)?-1:((x>y)?1:0);
}
```

This bug does not appear if I use the standard ghcjs 8.0.1 stack setup

```
resolver: lts-7.19

compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9
```

Eg. GHCJS 8.0.1 generated code looks like this

```
function h$$pY()
{
  var a = h$r1;
  var b = h$stack[(h$sp - 1)];
  h$sp -= 2;
  var c = h$jsstringCompare(b, a.d1);
  var d = c;
  var e = h$tagToEnum(((d + 1) | 0));
  if((e.f.a === 3))
  {
    return h$e(h$baseZCGHCziShowzishows19);
  }
  else
  {
    return h$e(h$baseZCGHCziShowzishows20);
  };
};
```

@alexanderkjeldaas, since I'm using your ghcjs 8.4 setup, have you also noticed that all JSString comparisons are always EQ?
