### ISSUE TITLE
Build stucks when compiling a project with Stack

### ISSUE THREAD

**Issue by osoftware** [ghcjs/ghcjs#745]
I've (supposedly) successfully built and booted 8.6 branch on Ubuntu 18.10 and made Stack recognize it with the following stack.yaml:

```
resolver: lts-13.12
compiler: ghcjs-8.6.0.1_ghc-8.6.2
setup-info:
  ghcjs:
    source:
      ghcjs-8.6.0.1_ghc-8.6.2:
        url: /home/*******/repos/ghcjs.tar.xz
```

However, when I try to build my project, it shows some initial progress, then gets stuck.

```
Building a GHCJS project. Note that GHCJS support in Stack is EXPERIMENTAL
base16-bytestring-0.1.1.6: configure
base16-bytestring-0.1.1.6: build
hashable-1.2.7.0: configure
base16-bytestring-0.1.1.6: copy/register
hashable-1.2.7.0: build
colour-2.3.4: configure
colour-2.3.4: build
integer-logarithms-1.0.2.2: configure
integer-logarithms-1.0.2.2: build
Progress 0/15
```

I also tried building some single dependencies and noticed they always get stuck at copy/register phase.

Not sure if it is related to Stack or Ghcjs.
